---

name: inception_v4-tflite

gops: 24.53
shapes:
  - [1, 3, 299, 299]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/inception_v4_299_quant.tflite
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --pixel_format rgb
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir


deploy:
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --asymmetric
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.90
      --correctness 0.99,0.93
      --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel
