---

name: densenet
gops: 5.69

model: $(home)/DenseNet_121.prototxt
weight: $(home)/DenseNet_121.caffemodel
int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

fp_compile_options:
  bmnetc
  --model $(model)
  --shapes [1,3,224,224]
  --weight $(weight)
  --target $(target)
  --opt 1
  --enable_profile true

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --weight $(weight)
    --test_iterations 1
    --net_name $(name)
    --postprocess_and_calc_score_class none
    --debug_cmd='use_fake_data_to_test;not_call_bmnetu'
    --target=$(target)
    --cali_iterations 1
    --input_shapes=[1,3,224,224]

bmnetu_options:
  --opt=1
  --cmp=True
  --target $(target)
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True

bmnetu_batch_sizes: [1, 4, 8, 16]
