---

name: resnet50-caffe
gops: 7.73

model: $(home)/ResNet-50-deploy.prototxt
weight: $(home)/ResNet-50-model.caffemodel

fp_compile_options:
  bmnetc
    --model $(model)
    --weight $(weight)
    --shapes [1,3,224,224]
    --net_name $(name)
    --target $(target)
    --enable_profile true

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)
    --weight $(weight)
    --input_shapes="[1,3,224,224]"
    --net_name=$(name)
    --cali_iterations=1
    --target=$(target)
    --test_iterations=1
    --debug_cmd="use_fake_data_to_test;not_suspend;not_call_bmnetu"

dataset:
  image_path: $(imagenet2012_val_set)
  image_label: $(imagenet2012_caffe_val_ground_truth)
  mean: [104, 117, 123]
  scale: 1
  size: 224

cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)
    --weight=$(weight)
    --input_shapes="[1,3,224,224]"
    --net_name=$(name)
    --cali_iterations=20
    --cali_image_path=$(imagenet2012_cali_set)
    --cali_image_preprocess='resize_h=224,resize_w=224;mean_value=104:117:123;scale=1'
    --target=$(target)
    --test_iterations=1
    --debug_cmd="not_call_bmnetu"

int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

bmnetu_batch_sizes: [1, 4]
bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target $(target)
  --enable_profile True

precision: true

harness:
  type: topk
  args:
    - name: FP32
      bmodel: $(workdir)/1b.fp.compilation/compilation.bmodel
    - name: INT8
      bmodel: $(workdir)/1b.compilation/compilation.bmodel
