---

iter_opt: --calculate_times

# LMDB output
data_dir: $(root)/data

# Cali dataset path for MLIR
imagenet2012_mlir_cali_set: $(root)/dataset/ILSVRC2012/caliset
coco2017_mlir_cali_set: $(root)/dataset/COCO2017/caliset

imagenet2012_val_set: $(root)/dataset/ILSVRC2012/ILSVRC2012_img_val
imagenet2012_caffe_val_ground_truth: $(root)/dataset/ILSVRC2012/caffe_val.txt

coco2017_val_set: $(root)/dataset/COCO2017/val2017
coco2017_anno: $(root)/dataset/COCO2017/annotations

default_cases:
  - vision/classification/LeNet
  - vision/classification/inception_v4
  - vision/classification/ResNet50-Caffe
  - vision/detection/yolov5


lfw_val_set: $(root)/dataset/lfw/lfw_mtcnnpy_160.tar
lfw_cali_set: $(root)/dataset/lfw/caliset/
lfw_pairs: $(root)/dataset/lfw/pairs.txt