---

iter_opt: --calculate_times

# LMDB output
data_dir: $(root)/data

# Cali dataset path for MLIR
imagenet2012_mlir_cali_set: $(root)/dataset/ILSVRC2012/caliset
coco2017_mlir_cali_set: $(root)/dataset/COCO2017/caliset

imagenet2012_val_set: $(root)/dataset/ILSVRC2012/ILSVRC2012_img_val
imagenet2012_caffe_val_ground_truth: $(root)/dataset/ILSVRC2012/caffe_val.list
