---

name: ScoringIds

model: $(home)/ScoringIds.pt

time: true
precision: true
runtime_cmp: false

BM1684X:
  build_env:
    - BMCOMPILER_FORCE_GLOBAL_LAYER_BY_ID=a
    - BMCOMPILER_BFLOAT16_LAYER_TYPES=

  fp_compile_options:
    python3 -m bmnetp
    --model $(model)
    --shapes '[458,20,30],[2,458,20,30],[458,2,20,30],[458],[1]'
    --target $(target)
    --enable_profile True
    --opt 1
    --dyn True
    --cmp 0
