
name: dahua_yolov3
gops: [1.517254]

model: $(home)/yolov3_jit.pt

fp32_compile_options:
  python3 -m bmnetp
    --model $(model)
    --shapes [[1,3,416,416]]
    --net_name $(name)
    --target BM1684X
    --enable_profile True

cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)
    --input_shapes="[1,3,416,416]"
    --net_name=$(name)
    --cali_iterations=10
    --cali_image_path=$(root)/../dataset/val2017
    --cali_image_preprocess='resize_h=416,resize_w=416;scale=0.003921569,bgr2rgb=True'
    --target=BM1684X
    --try_cali_accuracy_opt='-fpfwd_outputs=< 28 >86,< 28 >55,< 28 >18'
    --test_iterations=1
    --debug_cmd="not_call_bmnetu"

int8_model: $(workdir)/$(name)_bmnetp_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetp.int8umodel

bmnetu_batch_sizes: [1,4]    
bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target BM1684X
  --enable_profile True

precision: true

harness:
  type: map
  args:
    - name: FP32
      bmodel: $(workdir)/1b.fp32.compilation/compilation.bmodel
    - name: INT8
      bmodel: $(workdir)/1b.compilation/compilation.bmodel
