---

name: resnet50-v2

gops: 8.207398376

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/resnet50-v2-7.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [[1,3,224,224]]
    --resize_dims 256,256
    --mean 123.675,116.28,103.53
    --scale 0.0171,0.0175,0.0174
    --pixel_format rgb
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(imagenet2012_mlir_cali_set)
    --input_num 100
    -o $(workdir)/$(name).calitable

deploy:
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(workdir)/$(name).calitable
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.97,0.76
      --correctness 0.99,0.93
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --asymmetric
      --calibration_table $(workdir)/$(name).calitable
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.96,0.73
      --correctness 0.99,0.93
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
