---

name: efficientnet-lite4

gops: [2.711832160]
shapes:
  - [1, 224, 224, 3]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/efficientnet-lite4-11.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --resize_dims 256,256
    --mean 127,127,127
    --scale 0.0078125,0.0078125,0.0078125
    --pixel_format rgb
    --channel_format=nhwc
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/transformed.mlir
#     --dataset $(imagenet2012_mlir_cali_set)
#     --input_num 100
#     -o $(workdir)/$(name).calitable

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(home)/cali_table
      --quant_input
      --quant_output
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.98,0.85
      --correctness 0.99,0.90
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --asymmetric
      --calibration_table $(home)/cali_table
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.96,0.73
      --correctness 0.99,0.90
      --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel
