---

name: ppyoloe_crn_x_300e_coco
gops: 10.21

model: $(home)/ppyoloe_crn_x_300e_coco/

fp_compile_options:
  python3 -m bmpaddle
    --model $(model)
    --shapes [[1,3,640,640],[1,2]]
    --net_name $(name)
    --input_names "image,scale_factor"
    --descs "[1,fp32,1,1]"
    --output_names "multiclass_nms3_0.tmp_0,multiclass_nms3_0.tmp_2"
    --target BM1684X
    --enable_profile True

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)/model.pdmodel
    --input_shapes="[1,3,640,640];[1,2]"
    --input_names="image,scale_factor"
    --output_names="multiclass_nms3_0.tmp_0,multiclass_nms3_0.tmp_2"
    --input_descs="[1,fp32,1,1]"
    --net_name=$(name)
    --cali_iterations=1
    --target=BM1684X
    --test_iterations=1
    --debug_cmd="use_fake_data_to_test;not_suspend;not_call_bmnetu"

# int8_model: $(workdir)/$(name)_bmpaddle_deploy_int8_unique_top.prototxt
# int8_weight: $(workdir)/$(name)_bmpaddle.int8umodel

# bmnetu_batch_sizes: [1, 4]
# bmnetu_options:
#   --model $(int8_model)
#   --weight $(int8_weight)
#   --target BM1684X
#   --enable_profile True

# precision: false
