---

name: resnet50
gops: 2.42

model: $(home)/resnet50.onnx

precision: true

fp_compile_options:
  python3 -m bmneto
    --model $(model)
    --shapes [1,3,32,32]
    --net_name $(name)
    --target BM1684X
    --enable_profile true
    --cmp false

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --input_shapes "[1,3,32,32]"
    --net_name $(name)
    --test_iterations 1
    --target BM1684X
    --cali_iterations 1
    --debug_cmd "use_fake_data_to_test;not_suspend;not_call_bmnetu"

cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --input_shapes "[1,3,32,32]"
    --net_name $(name)
    --cali_iterations 200
    --cali_lmdb $(cifar100_cali_lmdb)
    --target BM1684X
    --test_iterations 1
    --debug_cmd "not_suspend;not_call_bmnetu"

int8_model: $(workdir)/$(name)_bmneto_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmneto.int8umodel

bmnetu_batch_sizes: [1, 3]
bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target BM1684X
  --cmp False
  --enable_profile True

dataset:
  image_path: $(cifar100_val_set)
  mean: [129.304, 124.070, 112.434]
  scale: [0.0146692093, 0.0152923905, 0.0142009145]

harness:
  type: cifar100_topk
  args:
    - name: FP32
      bmodel: $(workdir)/1b.fp.compilation/compilation.bmodel
    - name: INT8
      bmodel: $(workdir)/1b.compilation/compilation.bmodel
