---

name: yolov5
gops: 10.21

model: $(home)/yolov5s-4.0-640384_jit.pt

fp32_compile_options:
  python3 -m bmnetp
    --model $(model)
    --shapes [[1,3,640,384]]
    --net_name $(name)
    --target BM1684X
    --enable_profile True

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)
    --input_shapes="[1,3,640,384]"
    --net_name=$(name)
    --cali_iterations=1
    --target=BM1684X
    --try_cali_accuracy_opt='-fpfwd_outputs=< 24 >18,< 24 >55,< 24 >86'
    --test_iterations=1
    --debug_cmd="use_fake_data_to_test;not_suspend;not_call_bmnetu"

cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)
    --input_shapes="[1,3,640,384]"
    --net_name=$(name)
    --cali_iterations=100
    --cali_image_path=$(root)/dataset/val2017
    --cali_image_preprocess='resize_h=640,resize_w=384;scale=0.003921569,bgr2rgb=True'
    --target=BM1684X
    --try_cali_accuracy_opt='-fpfwd_outputs=< 24 >18,< 24 >55,< 24 >86'
    --test_iterations=1
    --debug_cmd="not_call_bmnetu"

int8_model: $(workdir)/$(name)_bmnetp_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetp.int8umodel

bmnetu_batch_sizes: [1, 4]
bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target BM1684X
  --enable_profile True

precision: true

harness:
  type: yolo
  args:
    - name: FP32
      bmodel: $(workdir)/1b.fp32.compilation/compilation.bmodel
      imagedir: $(root)/dataset/val2017
      anno: $(root)/dataset/annotations/instances_val2017.json
    - name: INT8
      bmodel: $(workdir)/1b.compilation/compilation.bmodel
      imagedir: $(root)/dataset/val2017
      anno: $(root)/dataset/annotations/instances_val2017.json
