---

name: yolov5l-5
gops: 107.5

model: $(home)/yolov5l-5.0.pt
precision: true

BM1684X:
  fp_loops:
    - build_env: [  ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

  cali:
    python3 -m ufw.cali.cali_model
      --model=$(model)
      --input_shapes="[1,3,640,640]"
      --net_name=$(name)
      --cali_iterations=100
      --cali_image_path=$(coco2017_cali_set)
      --cali_image_preprocess='resize_h=640,resize_w=640;scale=0.003921569,bgr2rgb=True'
      --target=$(target)
      --try_cali_accuracy_opt
          '-fpfwd_outputs=< 24 >14,< 24 >51,< 24 >82;-asym_threshold=true'
      --test_iterations=1
      --debug_cmd="not_call_bmnetu"

BM1684:
  fp_outdir_template: "{}b.fp32.compilation"

  cali:
    python3 -m ufw.cali.cali_model
      --model=$(model)
      --input_shapes="[1,3,640,640]"
      --net_name=$(name)
      --cali_iterations=100
      --cali_image_path=$(coco2017_cali_set)
      --cali_image_preprocess='resize_h=640,resize_w=640;scale=0.003921569,bgr2rgb=True'
      --target=$(target)
      --try_cali_accuracy_opt
          '-fpfwd_outputs=< 24 >14,< 24 >51,< 24 >82'
      --test_iterations=1
      --debug_cmd="not_call_bmnetu"

fp_compile_options:
  python3 -m bmnetp
    --model $(model)
    --shapes [[1,3,640,640]]
    --net_name $(name)
    --target $(target)
    --enable_profile True

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)
    --input_shapes="[1,3,640,640]"
    --net_name=$(name)
    --cali_iterations=1
    --target=$(target)
    --try_cali_accuracy_opt='-fpfwd_outputs=< 24 >14,< 24 >51,< 24 >82'
    --test_iterations=1
    --debug_cmd="use_fake_data_to_test;not_suspend;not_call_bmnetu"


int8_model: $(workdir)/$(name)_bmnetp_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetp.int8umodel

bmnetu_batch_sizes: [1, 4]
bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target $(target)
  --enable_profile True


dataset:
  imagedir: $(coco2017_val_set)
  anno: $(coco2017_anno)/instances_val2017.json

harness:
  type: yolo
  args:
    - name: FP32
      bmodel: $(workdir)/1b.fp32.compilation/compilation.bmodel
    - name: INT8
      bmodel: $(workdir)/1b.compilation/compilation.bmodel
