---

name: vgg11
gops: 15.2

model: $(home)/vgg11_traced.pt
int8_model: $(workdir)/$(name)_bmnetp_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetp.int8umodel

fp32_compile_options:
  python3 -m bmnetp
  --model $(model)
  --shapes [1,3,224,224]
  --target BM1684X
  --enable_profile True
  --opt 1
  --cmp 1

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --test_iterations 1
    --net_name $(name)
    --postprocess_and_calc_score_class none
    --debug_cmd='use_fake_data_to_test;to_umodel_not_cmp;not_call_bmnetu'
    --target=BM1684X
    --cali_iterations 1
    --input_shapes=[1,3,224,224]

bmnetu_options:
  --opt=2
  --cmp=False
  --target BM1684X
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True

bmnetu_batch_sizes: [1, 4, 8, 16]
